name: Notify devops on front-end changes

on:
  push:
    branches:
      - master

jobs:
  notify-devops:
    runs-on: ubuntu-latest

    steps:
      - name: Send dispatch to devops repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.tokrn_for_front }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"event_type": "front-changed"}' \
            https://api.github.com/repos/EdgarHarutyunyan2025/packer_task/dispatches
