name: Notify devops on front-end changes

on:
  push:
    branches:
      - master

jobs:
  notify-devops:
    runs-on: ubuntu-latest

    steps:
      - name: Send dispatch to devops repo
        run: |
            curl -H "Authorization: token ${{ secrets.TOKEN_FOR_FRONT }}" https://api.github.com/repos/EdgarHarutyunyan2025/packer_task
